export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const CREATE_TAB = "CREATE_TAB";
export const DELETE_TAB = "DELETE_TAB";
export const CHANGE_TAB = "CHANGE_TAB";
export const CHANGE_STATUS_OF_TAB_TO_CLOSED = "CHANGE_STATUS_OF_TAB_TO_CLOSED";

export const LOAD_ROOMS_SUCCESS = "LOAD_ROOMS_SUCCESS";
export const SERVER_SEND_MESSAGE = 'SERVER_SEND_MESSAGE';
export const ADMIN_JOIN_ROOM = 'ADMIN_JOIN_ROOM';
export const CHANGE_STATUS_OF_ROOM = 'CHANGE_STATUS_OF_ROOM';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const ADD_NEW_ROOM = 'ADD_NEW_ROOM';
export const ADMIN_SEND_MESSAGE = "ADMIN_SEND_MESSAGE";
export const UPDATE_MESSAGE_META_LINK = 'UPDATE_MESSAGE_META_LINK';
export const ADMIN_SEND_REQUEST_SOCKET = 'ADMIN_SEND_REQUEST_SOCKET';
export const ADMIN_RE_JOIN_ROOM = 'ADMIN_RE_JOIN_ROOM';
export const ADMIN_SEND_RATING = 'ADMIN_SEND_RATING';
export const CHANGE_STATUS_OF_TAB = 'CHANGE_STATUS_OF_TAB';
